### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bwieckow** [Geeks-Academy/terraform#210]
Update `Setting up AWS credentials` section. It should include Azure set up as well.

Useful example link: [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret )

**Comment by PiotrWachulec** [comment]
@bwieckow what exactly do you expect here? What should be described? And how detailed?
