### ISSUE TITLE
Set PROD variables

### ISSUE THREAD

**Issue by MaciejSpalek** [Geeks-Academy/terraform#248]
On the backend we have CLIENT_URL - used to manage CORS and on the frontend REACT_APP_API_URL. It's necessary to set them in the AWS. Current values of these variables are in the storage repository.

**Comment by bwieckow** [comment]
@hayuna @MaciejSpalek 
Parameters created with following names:
* /geeksacademy/structure_backend/CLIENT_URL
* /geeksacademy/structure_frontend/REACT_APP_API_URL
you can now use it in your `task_definition.json` files
