### ISSUE TITLE
[structure/frontend] Deployment Issue

### ISSUE THREAD

**Issue by hayuna** [Geeks-Academy/terraform#254]
Error: Failed to register task definition in ECS: When you are specifying container secrets, you must also specify a value for ‘executionRoleArn’.
14
Error: When you are specifying container secrets, you must also specify a value for ‘executionRoleArn’.

https://github.com/Geeks-Academy/structure/runs/2567670338?check_suite_focus=true#step:7:13

**Comment by bwieckow** [comment]
I noticed that deployment is working properly now. @hayuna please confirm if any action needed

**Comment by bwieckow** [comment]
Fixed with https://github.com/Geeks-Academy/structure/pull/104
